# Generated by Django 5.0.4 on 2024-06-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=32, unique=True)),
                ('date_visited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
