# Generated by Django 5.0.4 on 2024-07-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_visited',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de la visite'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Visiteur ID'),
        ),
    ]
