# Generated by Django 5.0.4 on 2024-05-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourproject', '0002_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='yourproject.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
