# Generated by Django 5.0.4 on 2024-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourproject', '0003_description_name_alter_description_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
