# Generated by Django 5.0.4 on 2024-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourproject', '0004_alter_description_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='description',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description du projet'),
        ),
    ]
