# Generated by Django 5.0.4 on 2024-05-13 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourproject', '0007_remove_devis_besoin_remove_devis_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='checked',
        ),
        migrations.AddField(
            model_name='devis',
            name='besoin',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='budget',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='date',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='posted_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
