# Generated by Django 5.0.4 on 2024-05-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourproject', '0008_remove_question_checked_devis_besoin_devis_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devis',
            old_name='posted_date',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='devis',
            old_name='author',
            new_name='question_1',
        ),
        migrations.RenameField(
            model_name='devis',
            old_name='phone',
            new_name='question_2',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='besoin',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='date',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='email',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='entreprise',
        ),
        migrations.AddField(
            model_name='devis',
            name='question_3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
