# Generated by Django 5.0.4 on 2024-06-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourproject', '0011_alter_question_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='update_at',
            new_name='created_at',
        ),
    ]
