# Generated by Django 5.0.4 on 2024-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_bds', '0002_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
