# Generated by Django 5.0.4 on 2024-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_bds', '0004_alter_team_facebook_alter_team_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=300)),
                ('response', models.CharField(max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
