# Generated by Django 5.0.4 on 2024-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_bds', '0005_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='ask',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ask',
            name='response',
            field=models.TextField(max_length=300),
        ),
    ]
