# Generated by Django 5.0.4 on 2024-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_bds', '0006_alter_ask_ask_alter_ask_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField()),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
        ),
    ]
