# Generated by Django 5.0.4 on 2024-05-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_bds', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contacts/%Y/%m/%d/', verbose_name='Fichier'),
        ),
    ]
