# Generated by Django 5.0.4 on 2024-06-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_bds', '0010_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask',
            options={'verbose_name': 'Question client', 'verbose_name_plural': 'Questions clients'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipe'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
    ]
